services:
  - type: web
    name: sellflow-api
    runtime: docker
    rootDir: sellflow-api
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    healthCheckPath: /up
    autoDeployTrigger: commit
    envVars:
      - key: APP_NAME
        value: SellFlow
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_PORT
        value: "5432"
      - key: DB_URL
        fromDatabase:
          name: sellflow-db
          property: connectionString
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: RUN_MIGRATIONS
        value: "true"
      - key: PRODUCT_IMAGE_DISK
        value: cloudinary
      - key: CLOUDINARY_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: sellflow-db
    plan: free
    region: singapore
    databaseName: sellflow
    user: sellflow
